export default [
  {
    id: 1,
    name: "Morongwa Mosopi",
    title: "Enterpreneur  |  Investor  |  Mentor",
    image: require("../../../assets/images/PersonCircleWhite.png"),
    date: "20 Feb 2021",
    time: "12:00",
    desc: "Programming is fun to learn, you just need a great mentor and practice",
  },
  {
    id: 2,
    name: "Mokhiri Phooko",
    title: "Enterpreneur  |  Investor  |  Mentor",
    image: require("../../../assets/images/PersonCircleWhite.png"),
    date: "15 Mar 2021",
    time: "06:00",
    desc: "Just Completed a new engine design for Mokhiri Dynamics",
  },
  {
    id: 3,
    name: "Mokhiri Phooko",
    title: "Enterpreneur  |  Investor  |  Mentor",
    image: require("../../../assets/images/PersonCircleWhite.png"),
    date: "28 Mar 2021",
    time: "15:36",
  },
  {
    id: 4,
    name: "Mokhiri Phooko",
    title: "Enterpreneur  |  Investor  |  Mentor",
    image: require("../../../assets/images/PersonCircleWhite.png"),
    date: "10 Jun 2021",
    time: "20:00",
    pic: require("../../../assets/images/FeedPic.png"),
  },
  {
    id: 5,
    name: "Mokhiri Phooko",
    title: "Enterpreneur  |  Investor  |  Mentor",
    image: require("../../../assets/images/PersonCircleWhite.png"),
    date: "28 Aug 2021",
    time: "17:00",
  },
];
